### ISSUE TITLE
mismatch between command example and accepted input

### ISSUE THREAD

**Issue by jmarkmorris** [intel/iodlr#33]
This document: https://software.intel.com/content/dam/develop/external/us/en/documents/runtimeperformanceoptimizationblueprint-largecodepages-q1update.pdf

Gives the following example: 
measure-perf-metric.sh -p 69772 -t 30 -m ITLB_stalls

Which gives an error, because "ITLB" is capitalized and the script requires lower case.

**Comment by suresh-srinivas** [comment]
Thank you for reporting this. We can update the blueprint document correctly.

**Comment by suresh-srinivas** [comment]
Blueprint is updated
