### ISSUE TITLE
invalid region boundaries

### ISSUE THREAD

**Issue by z-takele** [intel/iodlr#36]
I followed the readme at: accordingly I compiled the shared library (make -f Makefile.preload), and copied it to /usr/lib64.
Then when I try running applications by loading the library, I'm getting the following error:
```
$ LD_PRELOAD=/usr/lib64/liblppreload.so <app> 
Mapping to large pages failed: invalid region boundaries
```
I tested this on Ubuntu 20.04 and 18.04 (x86_64). 
I also I have huge-page enabled on the machines and tried with [madvise] and [always] settings, all with the same outcome giving the error above.  
This happens with all the applications that I tried.

**Comment by gabrielschulhof** [comment]
@z-takele can you please run `readelf -S --wide </path/to/your/binary>` and paste the output here?

**Comment by z-takele** [comment]
@gabrielschulhof sure, below is the output. 
```
$ readelf -S --wide  /usr/lib64/liblppreload.so
There are 32 section headers, starting at offset 0x202d90:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .note.gnu.property NOTE            00000000000002e0 0002e0 000020 00   A  0   0  8
  [ 2] .note.gnu.build-id NOTE            0000000000000300 000300 000024 00   A  0   0  4
  [ 3] .gnu.hash         GNU_HASH        0000000000000328 000328 00003c 00   A  4   0  8
  [ 4] .dynsym           DYNSYM          0000000000000368 000368 0002d0 18   A  5   1  8
  [ 5] .dynstr           STRTAB          0000000000000638 000638 0001c9 00   A  0   0  1
  [ 6] .gnu.version      VERSYM          0000000000000802 000802 00003c 02   A  4   0  2
  [ 7] .gnu.version_r    VERNEED         0000000000000840 000840 000060 00   A  5   1  8
  [ 8] .rela.dyn         RELA            00000000000008a0 0008a0 0005e8 18   A  4   0  8
  [ 9] .rela.plt         RELA            0000000000000e88 000e88 0001f8 18  AI  4  25  8
  [10] .init             PROGBITS        0000000000002000 002000 00001b 00  AX  0   0  4
  [11] .plt              PROGBITS        0000000000002020 002020 000160 10  AX  0   0 16
  [12] .plt.got          PROGBITS        0000000000002180 002180 000010 10  AX  0   0 16
  [13] .plt.sec          PROGBITS        0000000000002190 002190 000150 10  AX  0   0 16
  [14] .text             PROGBITS        00000000000022e0 0022e0 000a19 00  AX  0   0 16
  [15] lpstub            PROGBITS        0000000000200000 200000 000182 00  AX  0   0 2097152
  [16] .fini             PROGBITS        0000000000200184 200184 00000d 00  AX  0   0  4
  [17] .rodata           PROGBITS        0000000000201000 201000 00087b 01 AMS  0   0  8
  [18] .eh_frame_hdr     PROGBITS        000000000020187c 20187c 000064 00   A  0   0  4
  [19] .eh_frame         PROGBITS        00000000002018e0 2018e0 000238 00   A  0   0  8
  [20] .init_array       INIT_ARRAY      0000000000202c48 201c48 000010 08  WA  0   0  8
  [21] .fini_array       FINI_ARRAY      0000000000202c58 201c58 000008 08  WA  0   0  8
  [22] .data.rel.ro      PROGBITS        0000000000202c60 201c60 0001b0 00  WA  0   0 32
  [23] .dynamic          DYNAMIC         0000000000202e10 201e10 0001c0 10  WA  5   0  8
  [24] .got              PROGBITS        0000000000202fd0 201fd0 000028 08  WA  0   0  8
  [25] .got.plt          PROGBITS        0000000000203000 202000 0000c0 08  WA  0   0  8
  [26] .data             PROGBITS        00000000002030c0 2020c0 000008 00  WA  0   0  8
  [27] .bss              NOBITS          00000000002030c8 2020c8 000008 00  WA  0   0  1
  [28] .comment          PROGBITS        0000000000000000 2020c8 00002a 01  MS  0   0  1
  [29] .symtab           SYMTAB          0000000000000000 2020f8 000798 18     30  52  8
  [30] .strtab           STRTAB          0000000000000000 202890 0003dc 00      0   0  1
  [31] .shstrtab         STRTAB          0000000000000000 202c6c 000121 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  l (large), p (processor specific)
```

**Comment by gabrielschulhof** [comment]
@z-takele I did not mean the output for `/usr/lib64/liblppreload.so` but for the binary to which you are attempting to attach `liblppreload.so`.

You wrote
```
$ LD_PRELOAD=/usr/lib64/liblppreload.so <app> 
```
So I need the output for
```
readelf -S --wide <app>
```

I'm sorry I was not clear!

**Comment by z-takele** [comment]
Sure, here is the output of one of the binaries I tried. 
```
$ readelf -S --wide ebizzy
There are 31 section headers, starting at offset 0x52a8:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .interp           PROGBITS        0000000000000318 000318 00001c 00   A  0   0  1
  [ 2] .note.gnu.property NOTE            0000000000000338 000338 000020 00   A  0   0  8
  [ 3] .note.gnu.build-id NOTE            0000000000000358 000358 000024 00   A  0   0  4
  [ 4] .note.ABI-tag     NOTE            000000000000037c 00037c 000020 00   A  0   0  4
  [ 5] .gnu.hash         GNU_HASH        00000000000003a0 0003a0 000034 00   A  6   0  8
  [ 6] .dynsym           DYNSYM          00000000000003d8 0003d8 000318 18   A  7   1  8
  [ 7] .dynstr           STRTAB          00000000000006f0 0006f0 00016e 00   A  0   0  1
  [ 8] .gnu.version      VERSYM          000000000000085e 00085e 000042 02   A  6   0  2
  [ 9] .gnu.version_r    VERNEED         00000000000008a0 0008a0 000060 00   A  7   2  8
  [10] .rela.dyn         RELA            0000000000000900 000900 000108 18   A  6   0  8
  [11] .rela.plt         RELA            0000000000000a08 000a08 000240 18  AI  6  24  8
  [12] .init             PROGBITS        0000000000001000 001000 00001b 00  AX  0   0  4
  [13] .plt              PROGBITS        0000000000001020 001020 000190 10  AX  0   0 16
  [14] .plt.got          PROGBITS        00000000000011b0 0011b0 000010 10  AX  0   0 16
  [15] .plt.sec          PROGBITS        00000000000011c0 0011c0 000180 10  AX  0   0 16
  [16] .text             PROGBITS        0000000000001340 001340 001125 00  AX  0   0 16
  [17] .fini             PROGBITS        0000000000002468 002468 00000d 00  AX  0   0  4
  [18] .rodata           PROGBITS        0000000000003000 003000 000630 00   A  0   0  8
  [19] .eh_frame_hdr     PROGBITS        0000000000003630 003630 0000bc 00   A  0   0  4
  [20] .eh_frame         PROGBITS        00000000000036f0 0036f0 0002f0 00   A  0   0  8
  [21] .init_array       INIT_ARRAY      0000000000004cf0 003cf0 000008 08  WA  0   0  8
  [22] .fini_array       FINI_ARRAY      0000000000004cf8 003cf8 000008 08  WA  0   0  8
  [23] .dynamic          DYNAMIC         0000000000004d00 003d00 000200 10  WA  7   0  8
  [24] .got              PROGBITS        0000000000004f00 003f00 000100 08  WA  0   0  8
  [25] .data             PROGBITS        0000000000005000 004000 000014 00  WA  0   0  8
  [26] .bss              NOBITS          0000000000005020 004014 0000b8 00  WA  0   0 32
  [27] .comment          PROGBITS        0000000000000000 004014 00002a 01  MS  0   0  1
  [28] .symtab           SYMTAB          0000000000000000 004040 000be8 18     29  82  8
  [29] .strtab           STRTAB          0000000000000000 004c28 000566 00      0   0  1
  [30] .shstrtab         STRTAB          0000000000000000 00518e 00011a 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  l (large), p (processor specific)

```
But the same happens with all other applications I tried (even when attaching to shell commands (e.g. ls), or other apps installed my machine)

**Comment by gabrielschulhof** [comment]
@z-takele
```
...
[16] .text             PROGBITS        0000000000001340 001340 001125 00  AX  0   0 16
...
```
the size of your binary's `.text` section is only 4389 bytes. In order to re-map a portion of the `.text` section to 2 MiB pages, the `.text` section of the binary must be at least 2 MiB in size, and usually much larger, because it is usually not aligned to 2 MiB, meaning that its start address is not a multiple of 2 MiB, and so a portion of the code at the beginning of the `.text` section and a portion at the end must be skipped. If the section is too small, none is left for remapping. That, in turn, can cause such an error message.

**Comment by z-takele** [comment]
@gabrielschulhof  thanks, indeed that happens to be the problem. So I just tested with mysqld as in the provided example, it has larger text region (>2MiB).
Now, I get the following error.
```
$ LD_PRELOAD=/usr/lib64/liblppreload.so mysqld --help
Mapping to large pages failed: failed to open thp enablement status file
mysqld  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Starts the MySQL database server.

Usage: mysqld [OPTIONS]

For more help options (several pages), use mysqld --verbose --help.
```

but the file seems readable:
```
$ cat /sys/kernel/mm/transparent_hugepage/enabled
[always] madvise never
```

**Comment by gabrielschulhof** [comment]
Hmmm ... not sure why it is failing to open the file. One possible reason could be something like Debian's apparmor or Fedora's SELinux, which prevent an application from accessing paths that by the permissions they have may look like they're accessible.

**Comment by z-takele** [comment]
I'm running ubuntu 18.04, and tried it on 20.04 as well and got the same error. It's strange because the simple code I tried with correctly opens and reads the file whereas large_page.c fails to open the same file.

**Comment by gabrielschulhof** [comment]
Have you compiled liblppreload from source? If so, you can try inserting some `fprintf(stderr, ...)` statements to see exactly what the error is. For example, `fprintf(stderr, "errno was: %s\n", strerror(errno));` should tell you why it failed to open the file.

When I added liblppreload to mysqld, I made the change described at https://github.com/intel/iodlr/tree/master/large_page-c#modifying-a-systemd-service to enable liblppreload.

You can verify that a given binary has had its `.text` section remapped by running it, getting its PID and then reading /proc/PID/smaps. The `.text` section will look something like this:

```
00400000-0437e000 r-xp 00000000 fd:01 21102598                           /home/nix/.nvm/versions/node/v15.7.0/bin/node
Size:              65016 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:               26640 kB
Pss:               26640 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:     26640 kB
Private_Dirty:         0 kB
Referenced:        26640 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:            0
VmFlags: rd ex mr mw me dw sd hg
```

If you see the flag `hg` in the `VmFlags` field that means the mapping you're looking at has been re-mapped to large pages. That's how you can double-check that it worked.

You can also replace https://github.com/intel/iodlr/blob/master/large_page-c/large_page.c#L162-L188 with `*result = true;` and then it'll assume you have large pages enabled. Then, assuming it doesn't fail at some other point, you can double-check using the above method that the `.text` section was indeed successfully remapped.

**Comment by gabrielschulhof** [comment]
@z-takele as for the fact that it works from your simple code but not from mysqld, that is precisely how SELinux works. Under SELinux mysqld runs in a different (and less privileged) context than your app, such that for every file access that mysqld attempts to make, SELinux will check if mysqld's context is allowed to access the context in which the desired file is located.

**Comment by gabrielschulhof** [comment]
@z-takele another possibility is to disable apparmor for mysqld by running

```
sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
```

hopefully mysqld will subsequently be able to open the file.

**Comment by z-takele** [comment]
@gabrielschulhof thanks for the pointers! indeed it's apparmor's MAC permission that is blocking mysld from accessing the file. Now, it works fine and I verified it's mapped to hugepage. 

Another question, why the  does **.text** region must be > 2MiB to map to hugepages? why it's caveat of mapping smaller **.text** sizes (e.g. 4K) to large-page? Technically, I could barely find benchmarks or applications on my workstations that have **.text** segment > 2MiB. I was trying to perform some performance tests by attaching this shared library and see if any performance gain.

**Comment by gabrielschulhof** [comment]
@z-takele
```
2 MiB:   [                      ][                      ][                      ][                      ]
4 kiB:   [    ][    ][    ][xxxx][xxxx][xxxx][xxxx][xxxx][xxxx][xxxx][xxxx][xxxx][xxxx][x   ][    ][    ]
madvise: [    ][    ][    ][xxxx][xxxxxxxxxxxxxxxxxxxxxx][xxxxxxxxxxxxxxxxxxxxxx][xxxx][x   ][    ][    ]
```
* The first row shows 2 MiB boundaries.
* The second row shows 4 kiB boundaries (not to scale, because one 2 MiB chunk is 512 4 kiB chunks, not 4 of them). You can see that the `.text` section (marked "x") is aligned to a 4 kiB boundary.
* The third row shows what must be done in order to remap parts of `.text` to 2 MiB pages. The reason some of the `.text` section has to stay mapped to 4 kiB pages is that the `.text` section cannot be moved, because there are jump instructions inside it whose destination addresses are fixed either at compile time or at load time, but, in either case, before we get a chance to re-map. Thus, we must "snip" off
    * the beginning (if it's not 2 MiB-aligned) to maintain the same addresses, and
    * the end, because we don't have enough `.text` section to fill another 2 MiB page, and re-mapping whatever section follows the `.text` section may have unpredictable effects. Neither can we insert zeroes to fill the last page, and move the following section by a corresponding amount, because the relative location of the `.text` section and the section following it may also be hard-coded into the executable file, resulting in unpredictable behaviour.

Thus, if the entire `.text` section is less than 2 MiB then no part of it will fit in even a single 2 MiB page, and so cannot be re-mapped.

**Comment by z-takele** [comment]
@gabrielschulhof thanks for the brief explanation! Is there a particular use case or benchmark you recommend that I may test it with? I tried running mysql benchmark (sysbench), and then looking at tlb, instruction cache misses and the corresponding performance from the benchmark. But I couldn't see any difference while running with large page library attached vs without it. 

The nodejs installation that I have on my ubuntu machine has **<2MiB .text** segment. 

And please feel free to close this issue since this is not a bug.  thanks!

**Comment by gabrielschulhof** [comment]
@z-takele Ubuntu-provided Node.js uses Ubuntu-provided external libraries to provide OpenSSL, libuv, V8, etc. Thus, it is a small binary that links to other libraries.

The official Node.js distribution provides a binary that statically incorporates OpenSSL, libuv, V8, etc. Thus, the official binary has a much larger `.text` segment.

In https://software.intel.com/content/www/us/en/develop/articles/runtime-performance-optimization-blueprint-intel-architecture-optimization-with-large-code.html we quantify the performance benefits of re-mapping the offical Node.js `.text` section to large pages.

In terms of ITLB misses, when using liblppreload, the amount of benefit will depend on the percentage of `.text` that can be remapped and on the percentage of the code executed by the workload that resides on the re-mapped pages.

**Comment by uttampawar** [comment]
Closing the issue since user is satisfied with the Gabriel's explanation.
