### ISSUE TITLE
Metric** can't be derived. Missing pmus

### ISSUE THREAD

**Issue by saruagithub** [intel/iodlr#46]
Below is the bug hint: 
$ measure-perf-metric.sh -p 9650 -t 30 -m itlb_mpki
Initializing for metric: itlb_mpki
Checking if process with pid 9650 exists...
Profile application with process id: 9650
Collect perf data for 30 seconds
perf stat -e cycles,instructions,itlb_misses.walk_completed,itlb_misses.walk_completed_4k,itlb_ms.walk_completed_2m_4m,itlb_misses.walk_completed_1g

Calculating metric for: itlb_mpki

Final itlb_mpki metric

FORMULA: metric_ITLB_MPKI(%) = 1000*(a/b)
         where, a=itlb_misses.walk_completed
                b=instructions

**ERROR: metric_ITLB_MPKI can't be derived. Missing pmus**

Q ?  my perf version is 5.4, I just test on a zsh process (id 9650)

**Comment by uttampawar** [comment]
@saruagithub It seems that with perf version 5.4, itlb related counters are missing. Please provide list of supported counters from perf by running following command.

$ perf list

You may need to update perf version. On my test system with perf version 5.4.101, I'm able to derive this metric.
Here is what I get on my system.
System details: Ubuntu 20.04.2 LTS
Perf: perf version 5.4.101

$  ./measure-perf-metric.sh -t 30 -m itlb_mpki -a
Initializing for metric: itlb_mpki

--------------------------------------------------
Profiling whole system
--------------------------------------------------
Collect perf data for 30 seconds
perf stat -e cycles,instructions,itlb_misses.walk_completed,itlb_misses.walk_completed_4k,itlb_misses.walk_completed_2m_4m,itlb_misses.walk_completed_1g

Calculating metric for: itlb_mpki

=================================================
Final itlb_mpki metric
--------------------------------------------------
FORMULA: metric_ITLB_MPKI(%) = 1000*(a/b)
         where, a=itlb_misses.walk_completed
                b=instructions
=================================================
metric_ITLB_MPKI(%)=1.5343480000

=================================================
Final itlb_4k_mpki metric
--------------------------------------------------
FORMULA: metric_ITLB_4K_MPKI(%) = 1000*(a/b)
         where, a=itlb_misses.walk_completed_4k
                b=instructions
=================================================
metric_ITLB_4K_MPKI(%)=.3910170000


=================================================
Final itlb_2M_4M_mpki metric
--------------------------------------------------
FORMULA: metric_ITLB_2M_4M_MPKI(%) = 1000*(a/b)
         where, a=itlb_misses.walk_completed_2m_4m
                b=instructions
=================================================
metric_ITLB_2M_4M_MPKI(%)=1.1350680000


=================================================
Final itlb_1G_mpki metric
--------------------------------------------------
FORMULA: metric_ITLB_1G_MPKI(%) = 1000*(a/b)
         where, a=itlb_misses.walk_completed_1g
                b=instructions
=================================================
metric_ITLB_1G_MPKI(%)=0

HTH.

**Comment by saruagithub** [comment]
> @saruagithub It seems that with perf version 5.4, itlb related counters are missing. Please provide list of supported counters from perf by running following command.
> 
> $ perf list
> 
> You may need to update perf version. On my test system with perf version 5.4.101, I'm able to derive this metric.
> Here is what I get on my system.
> System details: Ubuntu 20.04.2 LTS
> Perf: perf version 5.4.101
> 
> ```
> $  ./measure-perf-metric.sh -t 30 -m itlb_mpki -a
> Initializing for metric: itlb_mpki
> 
> --------------------------------------------------
> Profiling whole system
> --------------------------------------------------
> Collect perf data for 30 seconds
> perf stat -e cycles,instructions,itlb_misses.walk_completed,itlb_misses.walk_completed_4k,itlb_misses.walk_completed_2m_4m,itlb_misses.walk_completed_1g
> 
> Calculating metric for: itlb_mpki
> 
> =================================================
> Final itlb_mpki metric
> --------------------------------------------------
> FORMULA: metric_ITLB_MPKI(%) = 1000*(a/b)
>          where, a=itlb_misses.walk_completed
>                 b=instructions
> =================================================
> metric_ITLB_MPKI(%)=1.5343480000
> 
> =================================================
> Final itlb_4k_mpki metric
> --------------------------------------------------
> FORMULA: metric_ITLB_4K_MPKI(%) = 1000*(a/b)
>          where, a=itlb_misses.walk_completed_4k
>                 b=instructions
> =================================================
> metric_ITLB_4K_MPKI(%)=.3910170000
> 
> 
> =================================================
> Final itlb_2M_4M_mpki metric
> --------------------------------------------------
> FORMULA: metric_ITLB_2M_4M_MPKI(%) = 1000*(a/b)
>          where, a=itlb_misses.walk_completed_2m_4m
>                 b=instructions
> =================================================
> metric_ITLB_2M_4M_MPKI(%)=1.1350680000
> 
> 
> =================================================
> Final itlb_1G_mpki metric
> --------------------------------------------------
> FORMULA: metric_ITLB_1G_MPKI(%) = 1000*(a/b)
>          where, a=itlb_misses.walk_completed_1g
>                 b=instructions
> =================================================
> metric_ITLB_1G_MPKI(%)=0
> 
> 
> HTH.
> ```

**Comment by saruagithub** [comment]
> > @saruagithub It seems that with perf version 5.4, itlb related counters are missing. Please provide list of supported counters from perf by running following command.
> > $ perf list
> > You may need to update perf version. On my test system with perf version 5.4.101, I'm able to derive this metric.
> > Here is what I get on my system.
> > System details: Ubuntu 20.04.2 LTS
> > Perf: perf version 5.4.101
> > ```
> > $  ./measure-perf-metric.sh -t 30 -m itlb_mpki -a
> > Initializing for metric: itlb_mpki
> > 
> > --------------------------------------------------
> > Profiling whole system
> > --------------------------------------------------
> > Collect perf data for 30 seconds
> > perf stat -e cycles,instructions,itlb_misses.walk_completed,itlb_misses.walk_completed_4k,itlb_misses.walk_completed_2m_4m,itlb_misses.walk_completed_1g
> > 
> > Calculating metric for: itlb_mpki
> > 
> > =================================================
> > Final itlb_mpki metric
> > --------------------------------------------------
> > FORMULA: metric_ITLB_MPKI(%) = 1000*(a/b)
> >          where, a=itlb_misses.walk_completed
> >                 b=instructions
> > =================================================
> > metric_ITLB_MPKI(%)=1.5343480000
> > 
> > =================================================
> > Final itlb_4k_mpki metric
> > --------------------------------------------------
> > FORMULA: metric_ITLB_4K_MPKI(%) = 1000*(a/b)
> >          where, a=itlb_misses.walk_completed_4k
> >                 b=instructions
> > =================================================
> > metric_ITLB_4K_MPKI(%)=.3910170000
> > 
> > 
> > =================================================
> > Final itlb_2M_4M_mpki metric
> > --------------------------------------------------
> > FORMULA: metric_ITLB_2M_4M_MPKI(%) = 1000*(a/b)
> >          where, a=itlb_misses.walk_completed_2m_4m
> >                 b=instructions
> > =================================================
> > metric_ITLB_2M_4M_MPKI(%)=1.1350680000
> > 
> > 
> > =================================================
> > Final itlb_1G_mpki metric
> > --------------------------------------------------
> > FORMULA: metric_ITLB_1G_MPKI(%) = 1000*(a/b)
> >          where, a=itlb_misses.walk_completed_1g
> >                 b=instructions
> > =================================================
> > metric_ITLB_1G_MPKI(%)=0
> > 
> > 
> > HTH.
> > ```

Yes, my perf version is 5.4.78,  $ perf list shows only these iTLB counters  related :
 iTLB-load-misses                                   [Hardware cache event]
  iTLB-loads  
 itlb.itlb_flush
       [Flushing of the Instruction TLB (ITLB) pages, includes 4k/2M/4M pages]
  itlb_misses.miss_causes_a_walk
       [Misses at all ITLB levels that cause page walks]
  itlb_misses.stlb_hit
       [Instruction fetch requests that miss the ITLB and hit the STLB]
  itlb_misses.walk_active
       [Cycles when at least one PMH is busy with a page walk for code (instruction fetch) request. EPT page walk duration are excluded in Skylake]
  itlb_misses.walk_completed
       [Code miss in all TLB levels causes a page walk that completes. (All page sizes)]
  itlb_misses.walk_completed_1g
       [Code miss in all TLB levels causes a page walk that completes. (1G)]
  itlb_misses.walk_completed_2m_4m
       [Code miss in all TLB levels causes a page walk that completes. (2M/4M)]
  itlb_misses.walk_completed_4k
       [Code miss in all TLB levels causes a page walk that completes. (4K)]
  itlb_misses.walk_pending
       [Counts 1 per cycle for each PMH that is busy with a page walk for an instruction fetch request. EPT page walk duration are excluded in Skylake]
  tlb_flush.dtlb_thread
       [DTLB flush attempts of the thread-specific entries]
  tlb_flush.stlb_any
       [STLB flush attempts]
