### ISSUE TITLE
Failure on building "wp4.2_php7.4_base_querycacheoff_http".

### ISSUE THREAD

**Issue by LeiW000** [intel/iodlr#59]
I tried to build  "wp4.2_php7.4_base_querycacheoff_http". But it fails with the error messages below.

` docker-compose build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --build-arg no_proxy=$no_proxy --no-cache wp4.2_php7.4_base_querycacheoff_http`

Step 21/31 : RUN echo "soft nofile 1000000\nhard nofile 1000000" | sudo tee -a /etc/security/limits.conf
 ---> Running in 4564fbdeacf4
soft nofile 1000000
hard nofile 1000000
Removing intermediate container 4564fbdeacf4
 ---> 38061c225a4e
Step 22/31 : COPY files/1s-bkm.j2 /home/${USERNAME}
 ---> 0edadcc0a1cd
Step 23/31 : COPY files/2s-bkm.j2 /home/${USERNAME}
 ---> d7f8830f7bba
Step 24/31 : RUN sudo cp /home/${USERNAME}/2s-bkm.j2 /etc/mysql/my.cnf
 ---> Running in 959cadd53374
Removing intermediate container 959cadd53374
 ---> 6f2581fe5fe8
Step 25/31 : RUN sudo service mysql start &&     sleep 1 &&     sudo mysqladmin -u root password "" &&     sudo mysql -u root -e "CREATE USER 'wp_bench'@'localhost' IDENTIFIED BY 'wp_bench'" &&     sudo mysql -u root -e "GRANT ALL PRIVILEGES on *.* to 'wp_bench'@'localhost' IDENTIFIED BY 'wp_bench'" &&     sudo mysql -u root -e "CREATE DATABASE wp_bench" &&     sudo mysql -u root -e "FLUSH PRIVILEGES" &&     sudo service mysql stop
 ---> Running in d6a900e201f9
 * Starting MariaDB database server mysqld
   ...done.
mysqladmin:
You cannot use 'password' command as mysqld runs
 with grant tables disabled (was started with --skip-grant-tables).
Use: "mysqladmin flush-privileges password '*'" instead
ERROR: Service 'wp4.2_php7.4_base_querycacheoff_http' failed to build: The command '/bin/sh -c sudo service mysql start &&     sleep 1 &&     sudo mysqladmin -u root password "" &&     sudo mysql -u root -e "CREATE USER 'wp_bench'@'localhost' IDENTIFIED BY 'wp_bench'" &&     sudo mysql -u root -e "GRANT ALL PRIVILEGES on *.* to 'wp_bench'@'localhost' IDENTIFIED BY 'wp_bench'" &&     sudo mysql -u root -e "CREATE DATABASE wp_bench" &&     sudo mysql -u root -e "FLUSH PRIVILEGES" &&     sudo service mysql stop' returned a non-zero code: 255

**Comment by LeiW000** [comment]
I feel that it is a critical issue, which needs to be fixed as soon as possible.

**Comment by PeterYang12** [comment]
Fixed this issue in this PR https://github.com/intel/iodlr/pull/60

**Comment by LeiW000** [comment]
Close it as the issue has been fixed.
