### ISSUE TITLE
dev-refactoring: "docker-compose build" fails on dev-refactoring branch.

### ISSUE THREAD

**Issue by LeiW000** [intel/iodlr#66]
sudo -E docker-compose build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --build-arg no_proxy=$no_proxy --no-cache

............
Step 67/73 : RUN rm -rf nginx &&     git clone --depth 1 -b $ASYNCH_NGINX_TAG https://github.com/intel/asynch_mode_nginx.git nginx &&     cd nginx &&     ./configure --prefix=/usr/         --with-http_ssl_module --add-dynamic-module=modules/nginx_qat_module         --with-cc-opt="-DNGX_SECURE_MEM         -I /opt/openssl/1.1.1k/include         -Wno-error=deprecated-declarations -Wimplicit-fallthrough=0"         --with-ld-opt="-Wl,-rpath=/opt/openssl/1.1.1k/lib         -L /opt/openssl/1.1.1k/lib" &&     make -j &&     sudo make install &&     rm -rf /home/${USERNAME}/nginx_build
 ---> Running in 8d9a9186c3ae
fatal: could not create work tree dir 'nginx': Permission denied
The command '/bin/sh -c rm -rf nginx &&     git clone --depth 1 -b $ASYNCH_NGINX_TAG https://github.com/intel/asynch_mode_nginx.git nginx &&     cd nginx &&     ./configure --prefix=/usr/         --with-http_ssl_module --add-dynamic-module=modules/nginx_qat_module         --with-cc-opt="-DNGX_SECURE_MEM         -I /opt/openssl/1.1.1k/include         -Wno-error=deprecated-declarations -Wimplicit-fallthrough=0"         --with-ld-opt="-Wl,-rpath=/opt/openssl/1.1.1k/lib         -L /opt/openssl/1.1.1k/lib" &&     make -j &&     sudo make install &&     rm -rf /home/${USERNAME}/nginx_build' returned a non-zero code: 128
ERROR: Service 'wp4.2_php7.4_opt_https' failed to build : Build failed

**Comment by pingzhaozz** [comment]
Seems a docker build tool problem. Before fix, pls use command like this to build:
`COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build --progress=plain --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --build-arg no_proxy=$no_proxy --no-cache wp5.6_php8.0_base_https`

**Comment by PeterYang12** [comment]
Fixed in commit 364de2f1ce562e82ea074040ac5fe558b210ab12
