### ISSUE TITLE
better add description of how to change siege concurrency number?

### ISSUE THREAD

**Issue by stkeke** [intel/iodlr#69]
In https://github.com/intel/iodlr/tree/master/containers/wordpress#siege-lifting-hang, better to add some description or code snippet to show how to change Siege concurrency number in our ```quickrun.sh``` or ```run.sh```. Some users, like me, might not be familiar with Siege usage.

**Comment by LeiW000** [comment]
The hang issue of Siege will be fixed in Siege 4.1.4. Then, that description will not be needed.

**Comment by LeiW000** [comment]
For the details of the hang issue, please see https://github.com/JoeDog/siege/issues/66.

**Comment by suresh-srinivas** [comment]
@LeiW000 nice work in collaboration in the community. You have verified the fix? I presume it solves the issue? We may want to update to the new Siege after the release.

**Comment by LeiW000** [comment]
@suresh-srinivas , Yes, I have verified the fix. The PR #72 has been filed to upgrade Siege.
