### ISSUE TITLE
Does iodlr enables hugepages for the .text section?

### ISSUE THREAD

**Issue by ibogosavljevic** [intel/iodlr#76]
What about .data and .bss section? Can I enable hugepages on those?

**Comment by LeiW000** [comment]
There is a tool in https://github.com/intel/iodlr/tree/master/large_page-c to help re-mapping the .text segment of the executable and dependent shared libraries. We use it in https://github.com/intel/iodlr/blob/master/containers/wordpress/wp_opt/Dockerfile for mysql.

For php in https://github.com/intel/iodlr/blob/master/containers/wordpress/wp_opt/Dockerfile, we enable USE_ZEND_ALLOC_HUGE_PAGES feature of PHP Zend engine. It means that the memory allocated by PHP vm will be in the huge pages.

For .data section, we provide an example to show how to utilize large pages for data. But it must make some changes to source code of your project. We did not do it for WordPress workload in the iodlr.

For .bss section, we don't provide any tool for it.
