### ISSUE TITLE
need update for AlderLake 

### ISSUE THREAD

**Issue by edisonchan** [intel/iodlr#77]
the metric for the scripts in tools folder does not work anymore for Alder Lake, could you make an update for it? 
There are many big differences for the Alder Lake perf events.

**Comment by LoongT4o** [comment]
I am sorry but could you explain the issue in more detail? Is [/iodlr/tools/measure-perf-metric.sh](https://github.com/intel/iodlr/blob/master/tools/measure-perf-metric.sh) not supporting Alder Lake?

**Comment by uttampawar** [comment]
@LoongT4o There are probably many differences in the perf events for Alderlake processor. We should do a comparison of individual events for current and Alderlake processor to derive those metrics. 
For e.g. to calculate itlb stalls the script needs two perf events and they are, "instructions", and "icache_64b.iftag_stall". We need to find equivalent event on Alder Lake if the exact event is not supported or changed. 

@edisonchan I don't have access to the Alderlake based machine, could you post latest perf events supported on Alderlake, please?

**Comment by suresh-srinivas** [comment]
ADL events are here https://github.com/intel/perfmon/tree/main/ADL/events

ADL is client part. This repo for Xeon only. Maybe revisit it during SPR
