### ISSUE TITLE
perf output will not have symbols 

### ISSUE THREAD

**Issue by suresh-srinivas** [intel/iodlr#9]
Tools like ` perf ` are no longer able to follow the symbols after the `.text` is remapped  and the perf output will not have the symbols like in the following figure. 

_Figure : perf output will not have the proper symbols after Large Page Mapping_
```
1.35% node perf-12142.map [.] 0x0000562eb19e86aa
1.19% node perf-12142.map [.] 0x0000562eb19e8803
0.71% node perf-12142.map [.] 0x0000562eb19e891f
```
The solution is to add additional code before the remapping and provide the static symbols to perf in `/tmp/perf-PID.map`.

**Comment by StephanDollberg** [comment]
Stumble into this issue on a native binary.

What I am confused by is why perf is struggeling but for example gdb can still resolve symbols just fine? With the way iodlr does the remapping the address shouldn't change as it remaps it to the same virtual address, right?

Also any idea on the exact format for the perf maps? Having to add an entry for every single symbol would be quite cumbersome if one could just provide a remapping range.

**Comment by LizYou** [comment]
@LeiW000  Could you help take a look at this issue?

**Comment by LeiW000** [comment]
Yes, I will take look at it.

**Comment by LeiW000** [comment]
@suresh-srinivas , could you give more details on how to reproduce the issue?

I tried to reproduce it with php. But I saw that some symbols were not shown correctly no matter if  Large Page Mapping is enabled. So I suspect that there is something wrong with your testing approach.

Without Large Page Mapping enabled:
```
   0.79%  php            php7.4             [.] 0x000000000027913c                                                              
   0.79%  php            php7.4             [.] 0x000000000027729f      
```

**Comment by LeiW000** [comment]
According to the blog below, I guess that it has something to do with the implementation of --perf-basic-prof support of javascript V8 engine. Becasue /tmp/perf-PID.map is generated with "--perf-basic-prof" support.

https://www.brendangregg.com/blog/2014-09-17/node-flame-graphs-on-linux.html

**Comment by StephanDollberg** [comment]
@LeiW000 thanks for taking a look.

If php is causing problems maybe just try any bigger (big enough so that we can remap) native binary. Something like clang should work or just generate some dumb code to get a large binary. I can reproduce with the later for example.

**Comment by LeiW000** [comment]
@StephanDollberg , thanks for your help. It seems that I can reproduce it with clang.

```
sudo perf report | grep JIT
     0.09%  clang           [JIT] tid 432687         [.] 0x00007f44cf8c3598
     0.09%  clang           [JIT] tid 432687         [.] 0x00007f44ce8e0683
     0.09%  clang           [JIT] tid 432687         [.] 0x00007f44d3f4d346
     0.09%  clang           [JIT] tid 432688         [.] 0x00007f7ca0a46eb0
     0.09%  clang           [JIT] tid 432688         [.] 0x00007f7ca0b80c0d
     0.09%  clang           [JIT] tid 432688         [.] 0x00007f7ca1ede496
     0.09%  clang           [JIT] tid 432688         [.] 0x00007f7ca0a37430
     0.09%  clang           [JIT] tid 432688         [.] 0x00007f7ca0b817bf
     0.09%  clang           [JIT] tid 432688         [.] 0x00007f7ca519a058
     0.09%  clang           [JIT] tid 432688         [.] 0x00007f7ca0a7eeea
     0.09%  clang           [JIT] tid 432688         [.] 0x00007f7ca5065295
     0.09%  clang           [JIT] tid 432688         [.] 0x00007f7ca562f1c0
     0.09%  clang           [JIT] tid 432688         [.] 0x00007f7ca0b896a0

```

**Comment by LeiW000** [comment]
For the case of remapping .txt sections, it is similar to JIT generated code. I think we have to rely on JIT symbol support of perf to show symbols correctly after .txt sections are remapped. It means that we need to provide
"/tmp/perf-$PID.map" file. Plese see below.

 https://lkml.org/lkml/2009/6/8/499 

For the format of .map file, please see function "perf_map_write_entry()". It is  simple.
https://github.com/jvm-profiling-tools/perf-map-agent/blob/master/src/c/perf-map-file.c

The next step is to see if we can add some codes  to generate perf-$PID.map file.

**Comment by suresh-srinivas** [comment]
@LeiW000 yes that is correct. One of the reasons `perf` is not able to get the symbols is due to anonymous text pages losing the original reference to the binary (see the `/proc/<pid>/maps`). 

This is not even a dynamic thing, it can be done even as a script. objdump the binary, and put symbols into the `/tmp/perf-$PID.map`

**Comment by StephanDollberg** [comment]
@suresh-srinivas any idea how gdb manages to resolves symbols out of box?

**Comment by StephanDollberg** [comment]
Hi,

Thanks for taking a look and sorry for the late reply. Only now got time to
look into this again.

I just tested this with a binary with stripped symbols but an external
debug symbols file.

The later is fine in general as one can point at the symbols file.

However, is there a reason for the specific nm args? Ie does anything speak
against using something like -aSC to also include debug symbols? Equally my
nm uses a lower cap t so that would need adding to the grep.

Do you see any problem with that? If not I'd be happy to prepare a patch.

Thanks,
Stephan

**Comment by StephanDollberg** [comment]
I have created https://github.com/intel/iodlr/pull/80 for this now
